config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :posts do
    resources :comments
  end
  resources :users
  resources :sessions

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :string
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :title, presence: true, length: {minimum: 3}
    validates :body, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  signin_name     :string
#  display_name    :string
#  password_digest :string
#  status          :string           default("available")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    has_many :posts
    validates :signin_name, presence: true, uniqueness: true, length: { in: 4..12}
    validates :display_name, presence: true
    validates :status, inclusion: { in: %w[available suspended]}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include HttpAcceptLanguage::AutoLocale
  include Pundit
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
     @post = Post.find(params[:post_id])   
     @post.comments.create(comment_params)
     redirect_to post_path(@post)
    end
    
    private
    
    def comment_params
        params.require(:comment).permit(:body)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @posts = Post.all.order(created_at:'desc')
    end
    
    def show
        @post = Post.find(params[:id])
    end

    def create
        # render plain:"受信パラメーター : #{params}"
        @post = Post.new(post_params.merge({user_id: session[:user_id]}))
        authorize @post
        if @post.save
            redirect_to posts_path
        else
            render "new"
        end
    end
    
    def new
        @post = Post.new
        authorize @post
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path
        else
            render "edit"
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
private

    def post_params
        params.require(:post).permit(:title, :body)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by(signin_name: params[:signin][:signin_name])
        
        if user && user.authenticate(params[:signin][:password])
            session[:user_id] = user.id.to_s
        end
        redirect_to posts_path
    end
    
    def destroy
        session.delete(:user_id)
        redirect_to posts_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to posts_path
        else
            render 'new'
        end
    end
    
    
   private
   
   def user_params
       params.require(:user).permit(:signin_name, :display_name, :password, :password_confirmation)
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= "container">
      <h1><%= link_to image_tag('logo.png',class: 'logo'),root_path %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<p>
    <%= f.text_field :title,placeholder: 'enter title' %>
    <% if @post.errors.messages[:title].any? %>
        <span class= "error"><%=@post.errors.messages[:title][0] %></span>
    <% end %>
</p>
<p>
    <%= f.text_area :body,placeholder: 'enter body text' %>
    <% if @post.errors.messages[:body].any? %>
        <span class= "error"><%=@post.errors.messages[:body][0] %></span>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/posts/_signin.html.erb
<% if current_user %>
    <div class='d-flex justify-content-end mb-2'>
        <span class = "mr-2">
            <%= current_user.display_name %>
        </span>
        <%= link_to t('.signout'),
        session_path(session[:user_id]),
        method: :delete,
        class: 'btn btn-sm btn-primary mr-2' %>
        <%= link_to t('.signup'), new_user_path, class: 'btn btn-sm btn-secondary' %>
    </div>
    <% else %>
    <% if User.all.any? %>
        <%= form_for :signin, url: sessions_path, html:{class: 'd-flex justify-content-end signin-form'} do |f| %>
            <%= f.text_field :signin_name, placeholder: 'signin name', class: 'form_control form-control-sm' %>
            <%= f.text_field :password, placeholder: 'password', class: 'form-control form-control-sm' %>
            <%= f.submit t('.signin'), class: 'btn btn-sm btn-primary' %>
        <% end %>
    <% else %>
        <%= link_to t('.signup'), new_user_path, class: 'btn btn-sm btn-secondary' %>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<div>
    <%= render 'signin' %>
</div>
<div class="d-flex justify-content-between">
    <h2>My Posts</h2>
    <% if current_user %>
        <%= button_to t('.add_new'), new_post_path, method: :get,class: 'btn btn-sm btn-primary' %>
    <% end %>
</div>

<ul class="list-group mt-2">
    <% @posts.each do |post| %>
        <li class="list-group-item d-flex justify-content-between">
            <div>
                <%= link_to post.title, post_path(post) %>
                <% if post.comments.any? %>
                    <span class="badge badge-primary badge-pill"><%= post.comments.size %></span>
                <% end %>
                <br />
                <span class='text-secondary'>
                    <%= l(post.created_at, format: :long) %>
                </span>
            </div>
            <% if current_user && current_user.id == post.user_id %>
                <div class="dropdown">
                    <button class="btn btn-sm btn-link dropdown-toggle p-0" data-toggle="dropdown">
                    </button>
                    <div class ="dropdown-menu">
                        <%= link_to t('.delete'),
                            post_path(post),
                            method: :delete,
                            class:'dropdown-item',
                            data: {confirm: t('.confirm')} %>
                        <%= link_to t('.edit'), edit_post_path(post), class:'dropdown-item' %>

                    </div>
                </div>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h2>Add New Post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p class="text-right">
<%= current_user.display_name %>
</p>
<p><%= @post.body %></p>

<h3>comments</h3>
<% if @post.comments.any? %>
<ul>
    <% @post.comments.each do |comment| %>
        <li><%= comment.body %></li>
    <% end %>
</ul>
<% end %>


<%= form_for [@post,@post.comments.build] do |f| %>
<p>
    <%= f.text_field :body %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<p>
    <%= f.text_field :signin_name,placeholder: 'enter signin name' %>
    <% if @user.errors.messages[:signin_name].any? %>
        <span class= "error"><%=@user.errors.messages[:signin_name][0] %></span>
    <% end %>
</p>
<p>
    <%= f.text_field :display_name,placeholder: 'enter display name' %>
    <% if @user.errors.messages[:display_name].any? %>
        <span class= "error"><%=@user.errors.messages[:display_name][0] %></span>
    <% end %>
</p>
<p>
    <%= f.text_field :password,placeholder: 'enter password' %>
    <% if @user.errors.messages[:password].any? %>
        <span class= "error"><%=@user.errors.messages[:password][0] %></span>
    <% end %>
</p>
<p>
    <%= f.text_field :password_confirmation,placeholder: 'enter password for confirmation' %>
    <% if @user.errors.messages[:password_confirmation].any? %>
        <span class= "error"><%=@user.errors.messages[:password_confirmation][0] %></span>
    <% end %>
</p>
<p>
    <%= f.submit class: 'btn btn-secondary' %>
</p>
<% end %>

<p>
    <%= link_to t('cancel'), posts_path, class: 'btn btn-secondary' %>
</p>

app/views/users/new.html.erb
<h2>Add Users</h2>
<%= render 'form' %>